<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.1.1" />
    <PackageReference Include="Microsoft.Identity.Web.TokenCache" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireOllama.ServiceDefaults\AspireOllama.ServiceDefaults.csproj" />
    <ProjectReference Include="..\AspireOllama.Shared\AspireOllama.Shared.csproj" />
  </ItemGroup>

</Project>
