<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AspireOllama.ServiceDefaults\AspireOllama.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\AspireOllama.Shared\AspireOllama.Shared.csproj" />
  </ItemGroup>

</Project>
