<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e3d23577-0655-40be-bd03-dc04a55a38b9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireOllama.ApiService\AspireOllama.ApiService.csproj" />
    <ProjectReference Include="..\AspireOllama.McpServer\AspireOllama.McpServer.csproj" />
    <ProjectReference Include="..\AspireOllama.Web\AspireOllama.Web.csproj" />
    <ProjectReference Include="..\A2A\AspireOllama.A2A.PlannerAgent\AspireOllama.A2A.PlannerAgent.csproj" />
    <ProjectReference Include="..\A2A\AspireOllama.A2A.ReviewerAgent\AspireOllama.A2A.ReviewerAgent.csproj" />
    <ProjectReference Include="..\A2A\AspireOllama.A2A.ResearchAgent\AspireOllama.A2A.ResearchAgent.csproj" />
    <ProjectReference Include="..\A2A\AspireOllama.A2A.CodeAgent\AspireOllama.A2A.CodeAgent.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.1.2" />
    <PackageReference Include="Aspire.Hosting.Yarp" Version="13.1.2" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" Version="13.1.1" />
    <PackageReference Include="Scalar.Aspire" Version="0.9.9" />
  </ItemGroup>

</Project>
